---
- name: Setup CloudStack master node with local db
  ansible.builtin.command: "/usr/bin/cloudstack-setup-databases 'cloud':'{{ mysql_cloud_password }}'@'localhost' --deploy-as=root:{{ mysql_root_password }} -i 127.0.0.1"
  when:
    - install_local_db is defined
    - install_local_db == 'true'
  changed_when: true

- name: Setup CloudStack master node
  ansible.builtin.command: >
    /usr/bin/cloudstack-setup-databases
    'cloud':'{{ mysql_cloud_password }}'@'{{ db_endpoint }}'
    --deploy-as=root:{{ mysql_root_password }} -i 127.0.0.1
  when:
    - nodetype is defined
    - nodetype == 'master'
    - install_local_db is undefined or install_local_db != 'true'
  changed_when: true

- name: Setup CloudStack slave node
  ansible.builtin.command: "/usr/bin/cloudstack-setup-databases 'cloud':'{{ mysql_cloud_password }}'@'{{ db_endpoint }}' -i 127.0.0.1"
  when:
    - nodetype is defined
    - nodetype == 'slave'
    - install_local_db is undefined or install_local_db != 'true'
  changed_when: true

- name: Setup CloudStack Manager
  ansible.builtin.command: /usr/bin/cloudstack-setup-management
  changed_when: true
